### ISSUE TITLE
security dependencies

### ISSUE THREAD

**Issue by brownsarahm** [fairnessforensics/detect_simpsons_paradox#7]
there are a number of security dependenies that we should fix, listed [on the alerts page under insights](https://github.com/fairnessforensics/detect_simpsons_paradox/network/alerts).

**Comment by brownsarahm** [comment]
Shine, I assigned this to you, but let me know if you're not sure how to do this.  It's the published repo not the working new one, so the process would be to clone this, branch, make the changes suggested, test to confirm it all still works, push the new branch and then submit a PR.

**Comment by Shine226** [comment]
The link above is not working.

**Comment by brownsarahm** [comment]
i changed your permissions, try again?

**Comment by Shine226** [comment]
The link works. I am working on this issue.

**Comment by Shine226** [comment]
I used virtualenv to upgrade urllib3, requests, django and notebook. Using the command "pip3 freeze > requirements.txt" to rewrite the requirements.txt file. 
Test follows the steps in detect_sp_example.ipynb file, and it still works.
All the work is under branch 'shinelocal', and I submitted a Pull Request.
